### ISSUE TITLE
Testing organizers and skipping specific parts

### ISSUE THREAD

**Issue by rafaltrojanowski** [collectiveidea/interactor#101]
Hi, 

I have little problem with testing Organizers.
I can't find any information about testing organizers except README.

So my question is what is the best way to skip step 2 in UpdateOrganizer spec?

```
class UpdateOrganizer
  include Interactor::Organizer

  organize ValidateInteractor, # step 1 
                 AuthorizeInteractor, # step 2
                 UpdateInteractor      # step 3
end

```

Could I stub AuthorizeInteractor object with rspec double()?
Other idea that comes to my mind is stubing AuthorizeInteractor internals.

In this case there is private method: user_has_permission?

Unfortunatelly

``` 
obj = double(AuthorizeInteractor)
allow(obj).to receive(:user_has_permission?).and_return(true)
```

not works.
I would appreciate any help.

**Comment by michaelherold** [comment]
The issue with mocking the interactor is that it's not an object that receives the message, but the class itself (i.e. `AuthorizeInteractor` receives `.call`, not an instance of `AuthorizeInteractor`).

You can stub the call by doing `expect(AuthorizeInteractor).to receive(:call!)`, but you want it to return a context-like object (an `OpenStruct` or a `Hash` works) instead of a boolean. Note that you have to mock out `.call!`, not `.call`, since Organizers use that internal method instead of the external interface.

As for what proper testing looks like, I'll let the maintainers comment on that. I haven't found a way of testing that I really like, yet.

**Comment by laserlemon** [comment]
Personally, I don't typically test my organizers. My rationale is that I haven't really written any code in my organizer. The only thing the organizer does is run its organized interactors in the proper order. That means to me that my responsibility is to thoroughly test the individual interactors, and to trust that the sequencing behavior of the organizer is well-tested in the Interactor library itself. I hope that helps!

**Comment by rafaltrojanowski** [comment]
@michaelherold Thanks, for your help. I will check it in my free time.
@laserlemon Interesting point of view.
