### ISSUE TITLE
Accidental rescuing Interactor::Failure errors in an interactor.

### ISSUE THREAD

**Issue by hedgesky** [collectiveidea/interactor#120]
Currently `context.fail!` [raises an error](https://docs.omniref.com/ruby/gems/interactor/3.1.0/files/lib/interactor/context.rb#line=101) but there is no mention about that in Readme. Therefore a user could accidentally rescue these errors. Example:

```ruby
class A
  include Interactor

  def call
    do_some_stuff
  rescue => e
    logger.error("#{e.class}: #{e.message}")
  end

  private

  def do_some_stuff
    context.fail!
  end
end
```

Here user tries to log unforeseen errors but instead finds such lines:

```
Interactor::Failure: #<Interactor::Context>
```

From my point of view, we should at least add information about that in README with possible solution:

```ruby
def call
  do_some_stuff
rescue Interactor::Failure
  raise
rescue => e
  puts "#{e.class}: #{e.message}"
end
```

But ideal solution is using `throw` instead of `raise`. It would stop execution (like `raise` does) and wouldn't require additional `rescues`. I can make a PR if you find this solution is acceptable.

**Comment by laserlemon** [comment]
Version 4.0 will use `throw` and `catch` rather than `raise` and `rescue` for this very reason. My attention is turning to development of 4.0, but I would be happy to merge a readme update with a brief mention of `context.fail!`'s internal behavior and a warning that using a blanket `rescue` in your interactor may swallow the failure.
