### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by elsurudo** [collectiveidea/interactor#155]
In my quest for something simpler than the interesting, but – in my opinion – over-engineered, Trailblazer, I stumbled upon this gem.

I really like the simple approach, and I've put it to good use in a few places in a current project.

However, is development dead? If I have some ideas and make a PR, does it have any chance of getting merged in? Will anyone even be up for a discussion about a new approach or feature? There are a bunch of old open PRs, and seemingly no action.

It'd be good to know before I get in too deep...

**Comment by braidn** [comment]
I would be totally down to help out as well here with bug fixes, code reviews etc.

**Comment by denispasin** [comment]
Count me in.

**Comment by FunkyloverOne** [comment]
@elsurudo @braidn @denispasin guys, you could take a look at this gem instead:
https://dry-rb.org/gems/dry-transaction/

**Comment by denispasin** [comment]
Thx @FunkyloverOne I already know (and use) dry-rb (mostly validation) a lot but I find interactor to be nicer to write and to use.

**Comment by braidn** [comment]
Ditto (same here). Find Interactor a bit nicer to write

**Comment by elsurudo** [comment]
I am in the same boat. Interactor is a bit more simple and free-form.

**Comment by denispasin** [comment]
Did any of you mailed @laserlemon ?

**Comment by natebird** [comment]
The repository has been fairly quiet since @laserlemon's Gemnasium was acquired by Gitlab. I wonder if that is keeping him busy.

**Comment by jdickey** [comment]
Guys, after using this for quite some time, I've been using and loving Hanami::Interactor for the last few months. Well-written and -documented; although not packaged completely separately, it's part of the lightweight [`hanami-utils` Gem](https://rubygems.org/gems/hanami-utils), which has other nice touches.

I've even dropped it in to a Roda app to replace a homegrown analogue (since collectiveidea/interactor has been so quiet so long).

* Tutorial/user docs [here](https://guides.hanamirb.org/architecture/interactors/);
* API docs for [Interactor interface](https://www.rubydoc.info/gems/hanami-utils/Hanami/Interactor/Interface) and [Result](https://www.rubydoc.info/gems/hanami-utils/Hanami/Interactor/Result) classes;
* Interactor [source](https://github.com/hanami/utils/blob/master/lib/hanami/interactor.rb).

HTH.

**Comment by braidn** [comment]
@jdickey is that Roda app out in the open on GitHub? Would love to see the structure around hanami-utils

**Comment by jdickey** [comment]
@braidn It's internal for now; I'll see if I can get it shaken loose.

As a side note, we got into Roda when we were experimenting with microservices; it's the easiest way to stand up high-performance endpoints in Ruby I'd yet found short of writing raw Rack. If all you're doing is APIs with JSON, Roda+dry-rb+interactors (in whatever form) will get you there. We're moving to Hanami because we like its philosophy of "build a monolith first, but in such a way that it's almost trivial to break things out as you justify doing so". But whatever you do, interactors make life *much* easier.

**Comment by braidn** [comment]
It’s good that you are getting a lot of mileage with Roda. I have been trying to push a stack like this with little luck. Having someone with a lot of success is oomf behind my push

**Comment by jdickey** [comment]
@braidn It's been a couple of months now, but drop me a message if I can kibitz on anything. What seems to be your problem?

**Comment by mtvillwock** [comment]
Wondering if this project is unmaintained now? @braidn Did you decide to go with Hanami interactors instead? Is @laserlemon still working on this?

**Comment by braidn** [comment]
I did end up with Hanami interactors. Not sure about the maintainability here but, I do see this frequently throughout Gemfiles

**Comment by jdickey** [comment]
@braidn Oddly enough, we've largely left "traditional" (collectiveidea or Hanami) interactors in favour of dry-monads' [do notation](https://dry-rb.org/gems/dry-monads/do-notation/). I  [blogged about it](https://jdickey.github.io/development/2019/04/13/an-interactor-or-a-use-case.html) back in April, with an example of what had been a Hanami interactor redone as a do-notation-using class.

Do notation, as I note in the blog post, allows us to make the sequence of steps as granular as we like (hello, low-level SRP) without having to do any (explicit) branching on status in the control method (`#call`, in the demo case). Each of the "step" methods in that class (`#authenticate_member`, `#find_member`, `#validate`) checks its own little piece of business logic, and then calls `Success` or `Failure` as appropriate to either continue or break the chain of methods `yield`ed to within `#call`.

There's apparently better ways to code some of those methods (particularly `#authenticate_member`) but I've sadly lost track of the pointer that someone gave me to that effect, apparently as a result of a reformat-after-imperfect-backup a few months ago.

Let me know what you think, @braidn. Thanks.

**Comment by gaffneyc** [comment]
Hey folks

Yes, Interactor is still being maintained since we use it a ton internally. I will say that it's taken a while to pick up the torch again since @laserlemon left Collective Idea for a new role. We're still using it a ton internally.

I've just rolled out 3.1.2 which fixes Context#fail! on Ruby 2.7
