### ISSUE TITLE
testing failure in minitest not working?

### ISSUE THREAD

**Issue by mengqing** [collectiveidea/interactor#81]
I have this test

```
class DummyInteractor
  include Interactor
  def call
    context.fail!
  end
end

require 'test'_helper'
class TestDummy < Minitest::Test
  def setup
    @interactor = DummyInteractor.new
    @context = @interactor.context
  end

  def test_should_be_failure
    @interactor.call

    assert_equal false, @context.success?
  end
end
```

However this is not passing, it returns Interactor::Failure: #<Interactor::Context>. If I do the DummyInteractor.call in the test_should_be_failure method then it works.

Is there anything that I'm doing it wrong?

Thanks

**Comment by michaelherold** [comment]
In practice, you won't be using `@interactor.call` since you call the interactor like `DummyInteractor.call(args)`, which taps into the `#run` method. If you switch your test around like the following, you can get the test to work:

```ruby
require 'interactor'

class DummyInteractor
  include Interactor

  def call
    context.fail!
  end
end

require 'minitest/autorun'

class TestDummy < Minitest::Test
  def setup
    @interactor = DummyInteractor.new
    @context = @interactor.context
  end

  def test_should_be_failure
    @interactor.run

    assert_equal true, @context.failure?
  end
end
```

Note: This is a self-contained test file, hence the additional requires.

Also, random: Why don't you use the `#failure?` method instead of checking for false on `#success?`? It'd be more idiomatic for the test.

**Comment by mengqing** [comment]
@michaelherold Thanks, that seem to have fixed it. It's just that this is not stated in the README..

**Comment by michaelherold** [comment]
I think the key thing that you want to take note of is that the interface for an interactor is the class-level `.call` method, not the instance level `#call`.
