### ISSUE TITLE
Conditional flow in organizers

### ISSUE THREAD

**Issue by mengqing** [collectiveidea/interactor#87]
What would be the ideal standard when I need a conditional flow in an organizer

eg: an user registration organizer involves creation of an user, and sending out a welcome email only if a certain criteria being met.

Also, would having an interactor call within an interactor considered a bad practice? Would it be better to use Organizer to organize the flow? But then again I need the flow to be conditional..

**Comment by emilford** [comment]
I'm not sure that there is an ideal standard.  I have my opinions, but the answers to your questions depends in part on personal preferences and in part on the specific requirements.  If you want to post some code, however, I'd be happy to give input.

**Comment by mengqing** [comment]
This is the kind of the flow that I've being doing for the moment so that SendWelcome class can be reused.. any suggestions/recommendations?

```ruby
class UserRegistration
  include Interactor::Organizer
 
  organize CreateUser, SendWelcome
end

class CreateUser
  include Interactor

  def call
  	# Creates the user
  	context.user = User.create

  	# Some logic to determine if
  	# Welcome email should send
  	context.stop_send = true unless context.user.confirmed?
  end
end

class SendWelcome
  include Interactor

  before do
  	context.fail!(
  	  message: 'Welcome email not required.'
  	) if context.stop_send
  end

  def call
  	# Send out welcome email
  end
end
```

**Comment by emilford** [comment]
@mengqing

Is there a case where a newly created user would already be `confirmed?`?  My initial reaction is to skip the checks entirely.  That is, keep user registration as both creating the user and sending a welcome email.  If you need to use `SendWelcome` in isolation (e.g., to re-send the welcome) or `CreateUser` in isolation, you still can.  Both could also be re-used in another organizer.

If that doesn't make sense for your requirements, I'd then at least reconsider using `context.fail!` in favor of a guard clause in `SendWelcome` (e.g., `return if context.user.confirmed?`).  If a user registers, is already marked as `confirmed?`, and therefore does not receive the welcome email, I would not consider that as a failure as it is the expected behavior.

**Comment by mengqing** [comment]
@emilford yes your comment makes sense. What I am trying to avoid is too many guard clauses which may make the code error prone, it would be a lot cleaner in my sense to be able to put guard clause in the organizer.

Also, would it be a bad practise to use an interactor within an interactor? This is so that I don't have to include all possible interactors in an organizer, but conditionally calls one in the interactor itself if needed. But doing this way I would loss the ability to rollback.
