### ISSUE TITLE
Better way to highlight organizers

### ISSUE THREAD

**Issue by adisos** [collectiveidea/interactor#96]
I have following interactors. From first sight it's difficult to say which of them is organizer. And I wondered how it can be solved. May be with naming classes or something else. Who else stuck with such a problem?

![image](https://cloud.githubusercontent.com/assets/592907/8955158/30dad6a4-360c-11e5-8dbc-cb02a3e8a852.png)

**Comment by michaelherold** [comment]
I don't name my organizers any differently than my interactors. The user doesn't really need to know it's an organizer since they have the same interface.

I've actually taken a name that was previously used for an interactors and switched it into an organizer because of some added business logic requirements. The fact that the name didn't change means that I don't have to touch any place where the interactor/organizer is used.

**Comment by adisos** [comment]
Yeah, I got you. Thanks for explanation.
